tasks:
  - name: aws-sam
    init: >
      cd /workspace
      && wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      && unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      && sudo ./sam-installation/install
  - name: cfn
    before: >
      bundle install
      && pip install cfn-lint
      && cargo install cfn-guard
      && gem install cfn-toml
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: >
      cd /workspace
      && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      && unzip awscliv2.zip
      && sudo ./aws/install
      && cd $THEIA_WORKSPACE_ROOT
      && bash bin/ecr/login
  - name: cdk
    before: >
      npm install aws-cdk -g
      && cd thumbing-serverless-cdk
      && npm install
  - name: postgres
    before: >
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      && echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      && sudo apt update
      && sudo apt install -y postgresql-client-13 libpq-dev
    command: >
      export GITPOD_IP=$(curl ifconfig.me)
      && source "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"
  - name: fargate
    before: >
      cd /workspace
      && curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      && sudo dpkg -i session-manager-plugin.deb
  - name: generate envs
    command: >
      "$THEIA_WORKSPACE_ROOT/bin/env/generate-env"
  - name: flask
    command: >
      cd backend-flask
      && pip install -r requirements.txt
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
ports:
  - name: frontend
    port: 3000
    visibility: public
  - name: backend
    port: 4567
    onOpen: ignore
    visibility: public
  - name: xray-daemon
    port: 2000
    onOpen: ignore
    visibility: public
  - name: postgres
    port: 5432
    onOpen: ignore
  - name: dynamodb
    port: 8000
    onOpen: ignore
